In [16]:
import pandas as pd
import numpy as np

In [17]:
Data=pd.read_excel("C:/Users/SAMSUNG/Desktop/세미_프로젝트2/정훈/수정데이터/숙박(최종).xlsx")
data=pd.DataFrame(Data)
data.drop(columns=data.columns[:2],inplace=True)

In [19]:
행정구역 = {'구좌':'구좌',
  '조천':'조천', 
  '화북': '동제주','봉개':'동제주', '회천':'동제주','용강':'동제주',
  '오라':'중제주','아라':'중제주','오등':'중제주','화북':'중제주','이도':'중제주','건입':'중제주','삼도':'중제주','용담':'중제주','일도':'중제주', 
  '도두':'서제주','이호':'서제주','외도':'서제주','내도':'서제주','도평':'서제주','노형':'서제주','연동':'서제주','강정':'서제주','도순':'서제주',
  '영남':'서제주','월평':'서제주','해안':'서제주', '노형':'서제주',
  '애월' :'애월',
  '성산':'성산',
  '한림':'한림',
  '표선':'표선',
  '남원':'남원',
  '한경':'한경',
  '안덕':'안덕',
  '영천':'동서귀','동흥':'동서귀','효돈':'동서귀','송산':'동서귀','신효':'동서귀','하효':'동서귀','서귀':'동서귀','보목':'동서귀','동홍':'동서귀',
  '대천':'중서귀','대륜':'중서귀','서홍':'중서귀', '강정':'중서귀','법환':'중서귀','서호':'중서귀','호근':'중서귀',
  '여래':'서서귀','중문':'서서귀','회수':'서서귀', '하원':'서서귀','대포':'서서귀', '색달':'서서귀', '하예':'서서귀', '상예':'서서귀',  
  '대정':'대정'}

In [20]:
#행정구역 설정 함수
def trans(x):
    for i in 행정구역.keys():
        try:
            if i in x:
                return 행정구역[i]
        except:
            break

In [23]:
data["행정구역"]=data["지번주소"].apply(lambda x:trans(x))
data.loc[data["행정구역"].isna(),"행정구역"]=data[data["행정구역"].isna()].apply(lambda x:trans(x))

In [24]:
add=pd.read_excel("C:/Users/SAMSUNG/Desktop/DataAnalysis/my_projects/02_semi_project2/제주공항에서숙박.xlsx") #각 숙박업에서 제주도까지의 거리

In [25]:
#Nan값 확인
add.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1263 entries, 0 to 1262
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1263 non-null   int64
 1   name        1263 non-null   object
 2   경도          1263 non-null   float64
 3   위도          1263 non-null   float64
 4   taxi        1263 non-null   int64
 5   toll        1263 non-null   int64
 6   거리(m)       1263 non-null   int64
 7   이동시간(초)     1263 non-null   int64
dtypes: float64(2), int64(5), object(1)
memory usage: 79.1+ KB

In [26]:
data1=data.set_index("타이틀")
data1.index.name=None
add.set_index("name",inplace=True)
add.index.name=None
#숙박업 데이터 + 해당 숙박업과 제주공항 사이의 거리
add_data=pd.merge(data,add,how="left",left_on="타이틀",right_on=add.index).drop(columns="Unnamed: 0")

In [27]:
add2=pd.read_excel("C:/Users/SAMSUNG/Desktop/세미_프로젝트2/정훈/수정데이터/음식점(최종).xlsx")
add3=pd.read_excel("C:/Users/SAMSUNG/Desktop/세미_프로젝트2/정훈/수정데이터/관광지(최종).xlsx")

In [29]:
Big_data=pd.concat([add_data,add2,add3]) #최종 데이터

In [30]:
Big_data.to_excel("C:/Users/SAMSUNG/Desktop/세미_프로젝트2/정훈/수정데이터/빅데이터.xlsx")

In [34]:
Big_data

,콘텐츠분류,타이틀,지번주소,도로명주소,위도_x,경도_x,탐나오연동여부,평점,소셜네트워크주소,조회수,...,경도_y,위도_y,taxi,toll,거리(m),이동시간(초),Unnamed: 0.1,Unnamed: 0,위도,경도
0,숙박,해피펜션,제주특별자치도 제주시 외도2동 317-1,제주특별자치도 제주시 월대1길 4,33.494110,126.43378,y,NaN,blog.naver.com/happycho25,979,...,126.433769,33.494102,7900.0,0.0,7169.0,995.0,NaN,NaN,NaN,NaN
1,숙박,빠담빠담게스트하우스,제주특별자치도 서귀포시 표선면 표선리 2093,제주특별자치도 서귀포시 표선면 돈오름로 198-4,33.329624,126.81827,y,5.0,NaN,4263,...,126.818263,33.329617,36400.0,0.0,43069.0,3729.0,NaN,NaN,NaN,NaN
2,숙박,빠담빠담게스트하우스,제주특별자치도 서귀포시 표선면 표선리 2093,제주특별자치도 서귀포시 표선면 돈오름로 198-4,33.329624,126.81827,y,5.0,NaN,4263,...,126.818263,33.329617,36400.0,0.0,43069.0,3729.0,NaN,NaN,NaN,NaN
3,숙박,빠담빠담게스트하우스,제주특별자치도 서귀포시 표선면 표선리 2093,제주특별자치도 서귀포시 표선면 돈오름로 198-4,33.329624,126.81827,y,5.0,NaN,4263,...,126.818263,33.329617,36400.0,0.0,43069.0,3729.0,NaN,NaN,NaN,NaN
4,숙박,빠담빠담게스트하우스,제주특별자치도 서귀포시 표선면 표선리 2093,제주특별자치도 서귀포시 표선면 돈오름로 198-4,33.329624,126.81827,y,5.0,NaN,4263,...,126.818263,33.329617,36400.0,0.0,43069.0,3729.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11158,관광지,방림원,제주특별자치도 제주시 한경면 용금로 864,제주특별자치도 제주시 한경면 용금로 864,NaN,NaN,y,4.0,blog.naver.com/banglimwon,14329,...,NaN,NaN,NaN,NaN,NaN,NaN,11473.0,11473.0,33.336983,126.268660
11159,관광지,방림원,제주특별자치도 제주시 한경면 용금로 864,제주특별자치도 제주시 한경면 용금로 864,NaN,NaN,y,4.0,blog.naver.com/banglimwon,14329,...,NaN,NaN,NaN,NaN,NaN,NaN,11474.0,11474.0,33.336983,126.268660
11160,관광지,방림원,제주특별자치도 제주시 한경면 용금로 864,제주특별자치도 제주시 한경면 용금로 864,NaN,NaN,y,4.0,blog.naver.com/banglimwon,14329,...,NaN,NaN,NaN,NaN,NaN,NaN,11475.0,11475.0,33.336983,126.268660
11161,관광지,곱닥한개,제주특별자치도 제주시 삼양이동 2101-10,제주특별자치도 제주시 설촌로10길 12,NaN,NaN,y,0.0,instagram.com/gobdakhan.dog,104,...,NaN,NaN,NaN,NaN,NaN,NaN,11476.0,11476.0,33.523885,126.582803
11162,관광지,놀자개,제주특별자치도 제주시 노형동 3702-2,제주특별자치도 제주시 오광로 143,NaN,NaN,y,0.0,instagram.com/ajdejfosem,122,...,NaN,NaN,NaN,NaN,NaN,NaN,11477.0,11477.0,33.483845,126.462201