In [1]:
import pandas as pd

In [2]:
기초수급자=pd.read_csv("./국민기초생활보장+연령별+일반수급자(구별)_20231003143933.csv")
주민등록=pd.read_csv("./주민등록연앙인구(연령별)_20231003144338.csv")
장애인=pd.read_csv("./장애인+현황(장애유형별_동별)_20231003144226.csv")

In [3]:
기초수급자

,시점,자치구별(1),자치구별(2),일반수급자,일반수급자.1,일반수급자.2,일반수급자.3,일반수급자.4,일반수급자.5,일반수급자.6,...,일반수급자.8,일반수급자.9,일반수급자.10,일반수급자.11,일반수급자.12,일반수급자.13,일반수급자.14,일반수급자.15,일반수급자.16,일반수급자.17
0,시점,자치구별(1),자치구별(2),소계,0~4세,5~9세,10~14세,15~19세,20~24세,25~29세,...,35~39세,40~44세,45~49세,50~54세,55~59세,60~64세,65~69세,70~74세,75~79세,80세이상
1,2012,합계,소계,188017,2817,5117,11478,19560,9447,2994,...,5857,12033,15917,17461,13789,10434,13881,17596,12943,13488
2,2012,합계,종로구,3057,33,67,164,220,99,38,...,91,189,259,278,246,196,307,351,231,245
3,2012,합계,중구,3498,23,65,148,268,126,36,...,91,171,287,369,326,233,339,414,281,281
4,2012,합계,용산구,4284,63,87,193,268,119,34,...,122,228,333,383,377,315,440,526,379,348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,2019,합계,관악구,15835,150,392,664,1095,726,340,...,420,588,1048,1220,1503,1475,1399,1366,1373,1759
205,2019,합계,서초구,5846,63,251,295,461,254,146,...,150,212,360,446,492,564,528,493,415,601
206,2019,합계,강남구,12290,184,294,493,798,607,306,...,359,422,689,897,1109,1317,1196,1184,1070,1153
207,2019,합계,송파구,13123,176,484,813,1176,681,299,...,385,530,888,1023,1095,1153,1069,1011,878,1212
208,2019,합계,강동구,11277,115,357,599,938,476,198,...,283,421,739,928,1082,1064,986,886,873,1138

In [4]:
주민등록

,동별(1),동별(2),성별(1),2013,2013.1,2013.2,2013.3,2013.4,2013.5,2013.6,...,2019.12,2019.13,2019.14,2019.15,2019.16,2019.17,2019.18,2019.19,2019.20,2019.21
0,동별(1),동별(2),성별(1),계,계,계,계,계,계,계,...,계,계,계,계,계,계,계,계,계,계
1,동별(1),동별(2),성별(1),소계,0~4세,5~9세,10~14세,15~19세,20~24세,25~29세,...,55~59세,60~64세,65~69세,70~74세,75~79세,80~84세,85~89세,90~94세,95~99세,100세 이상+
2,합계,소계,계,10012712,412727,403818,495012,621096,683039,781951,...,752147,668848,466086,370202,284617,166758,74381,26780,6436,851
3,합계,소계,남자,4940393,211790,207919,257037,325512,345172,386001,...,364170,317439,219729,170804,128223,66601,23816,6503,1500,146
4,합계,소계,여자,5072319,200938,195899,237975,295584,337868,395950,...,387978,351409,246358,199398,156394,100157,50565,20277,4937,705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,합계,송파구,남자,323719,14976,15130,18889,22579,23101,24637,...,24169,21535,15083,10850,6850,3386,1261,378,83,8
76,합계,송파구,여자,338674,14128,14044,17576,21302,22301,27277,...,26683,24097,15879,11085,7528,4954,2962,1294,322,48
77,합계,강동구,계,479184,20726,19748,24226,31539,33521,36074,...,35790,32633,22088,16111,10722,6097,2969,1215,281,42
78,합계,강동구,남자,239131,10694,10291,12772,17016,17654,18295,...,17127,15411,10716,7902,5071,2363,838,241,53,7
79,합계,강동구,여자,240053,10033,9457,11454,14524,15868,17780,...,18663,17222,11373,8209,5651,3735,2132,974,228,35

In [5]:
장애인

,동별(1),동별(2),2012,2012.1,2012.2,2012.3,2012.4,2012.5,2012.6,2012.7,...,2019.38,2019.39,2019.40,2019.41,2019.42,2019.43,2019.44,2019.45,2019.46,2019.47
0,동별(1),동별(2),합계,합계,합계,합계,합계,합계,합계,합계,...,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계
1,동별(1),동별(2),소계,소계,소계,지체,지체,지체,뇌병변,뇌병변,...,간,안면,안면,안면,장루요루,장루요루,장루요루,뇌전증,뇌전증,뇌전증
2,동별(1),동별(2),계,남자,여자,계,남자,여자,계,남자,...,여자,계,남자,여자,계,남자,여자,계,남자,여자
3,합계,소계,407528,237538,169990,208074,118130,89944,45041,26877,...,775,385,212,173,2855,1784,1071,1244,687,557
4,합계,종로구,6905,4020,2885,3467,1897,1570,774,475,...,11,6,3,3,34,21,13,20,11,9
5,합계,중구,6296,3650,2646,3279,1794,1485,680,434,...,8,5,2,3,36,26,10,22,13,9
6,합계,용산구,9225,5301,3924,4679,2570,2109,1049,634,...,16,6,5,1,68,41,27,20,11,9
7,합계,성동구,12256,7164,5092,6531,3659,2872,1315,816,...,23,15,8,7,85,52,33,39,24,15
8,합계,광진구,13187,7768,5419,6836,3934,2902,1407,869,...,18,8,5,3,105,81,24,49,29,20
9,합계,동대문구,16584,9740,6844,8978,5095,3883,1724,1054,...,42,19,9,10,110,72,38,46,25,21
10,합계,중랑구,20563,12070,8493,11226,6399,4827,2087,1239,...,39,16,6,10,161,102,59,70,31,39
11,합계,성북구,19507,11187,8320,10182,5634,4548,2239,1296,...,47,18,10,8,115,73,42,49,26,23
12,합계,강북구,17641,10150,7491,9002,5058,3944,1921,1214,...,34,10,6,4,134,87,47,52,34,18
13,합계,도봉구,14972,8747,6225,7557,4310,3247,1729,1013,...,39,16,9,7,136,84,52,42,29,13
14,합계,노원구,28299,15755,12544,14102,7776,6326,3243,1863,...,27,34,19,15,178,104,74,113,52,61
15,합계,은평구,21905,12951,8954,10400,5772,4628,2512,1575,...,41,25,15,10,164,95,69,68,39,29
16,합계,서대문구,12901,7264,5637,6473,3531,2942,1577,910,...,31,10,6,4,116,68,48,29,16,13
17,합계,마포구,14562,8300,6262,7297,4004,3293,1713,1008,...,26,10,5,5,109,67,42,34,22,12
18,합계,양천구,18106,10643,7463,9506,5595,3911,1925,1132,...,45,12,6,6,130,76,54,49,32,17
19,합계,강서구,27518,16041,11477,13637,7942,5695,2977,1788,...,50,36,20,16,182,118,64,120,66,54
20,합계,구로구,17821,10782,7039,9404,5632,3772,1802,1099,...,27,27,16,11,136,98,38,51,31,20
21,합계,금천구,11210,6870,4340,5886,3626,2260,1115,664,...,20,16,7,9,85,41,44,39,24,15
22,합계,영등포구,16033,9642,6391,8501,4930,3571,1651,1024,...,22,19,13,6,106,63,43,32,18,14
23,합계,동작구,15431,8890,6541,7749,4333,3416,1697,968,...,29,10,7,3,113,76,37,44,20,24
24,합계,관악구,20999,12312,8687,10866,6218,4648,2122,1281,...,32,14,8,6,137,80,57,59,35,24
25,합계,서초구,10702,6216,4486,5119,2827,2292,1351,770,...,27,2,2,-,79,52,27,26,12,14
26,합계,강남구,15641,8888,6753,7464,4147,3317,1811,1026,...,44,20,9,11,83,60,23,57,24,33
27,합계,송파구,20615,12030,8585,10382,5852,4530,2458,1422,...,40,12,8,4,145,90,55,57,38,19
28,합계,강동구,18649,11157,7492,9551,5595,3956,2162,1303,...,37,19,8,11,108,57,51,57,25,32