In [149]:
import pandas as pd

In [150]:
Data=pd.read_csv("./강우량_종힙.csv")

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_6484\2983805495.py:1: DtypeWarning: Columns (1,3,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  Data=pd.read_csv("./강우량_종힙.csv")

In [151]:
Data.drop([0,1],axis=0,inplace=True)
Data.drop(['Unnamed: 0'],axis=1,inplace=True)

In [152]:
Data.head(3)

,강우량_코드,강우량계명,구청_코드,구청명,시우량,일년누계,최대우량,송신지_자료수집_시각,수신서버_저장_시각
2,402,상계1동,104,노원구,0,57,4.5,2019-06-16 03:29:40,2019-06-16 03:30:00\n
3,402,상계1동,104,노원구,0,57,4.5,2019-06-16 03:30:40,2019-06-16 03:31:00\n
4,402,상계1동,104,노원구,0,57,4.5,2019-06-16 03:31:40,2019-06-16 03:31:58\n

In [153]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16390595 entries, 2 to 16390596
Data columns (total 9 columns):
 #   Column       Dtype
---  ------       -----
 0   강우량_코드       object
 1   강우량계명        object
 2   구청_코드        object
 3   구청명          object
 4   시우량          object
 5   일년누계         object
 6   최대우량         object
 7   송신지_자료수집_시각  object
 8   수신서버_저장_시각   object
dtypes: object(9)
memory usage: 1.1+ GB

In [154]:
Data[["시우량","일년누계","최대우량"]]=Data[["시우량","일년누계","최대우량"]].applymap(float)

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_6484\1361654110.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  Data[["시우량","일년누계","최대우량"]]=Data[["시우량","일년누계","최대우량"]].applymap(float)

In [155]:
use_Data=Data[Data["시우량"]!=0]
use_Data

,강우량_코드,강우량계명,구청_코드,구청명,시우량,일년누계,최대우량,송신지_자료수집_시각,수신서버_저장_시각
166,103,개포2동,101,강남구,1.5,78.0,4.5,2019-04-09 21:33:41,2019-04-09 21:34:41\n
168,103,개포2동,101,강남구,1.5,78.0,4.5,2019-04-09 21:34:40,2019-04-09 21:35:19\n
169,103,개포2동,101,강남구,1.5,78.0,4.5,2019-04-09 21:35:40,2019-04-09 21:36:39\n
170,103,개포2동,101,강남구,1.5,78.0,4.5,2019-04-09 21:36:40,2019-04-09 21:37:20\n
171,103,개포2동,101,강남구,1.5,78.0,4.5,2019-04-09 21:37:40,2019-04-09 21:38:31\n
...,...,...,...,...,...,...,...,...,...
16215679,702,면목P,107,중랑구,0.5,58.5,3.5,2019-03-31 00:09:41,2019-03-31 00:09:01\n
16215680,702,면목P,107,중랑구,0.5,58.5,3.5,2019-03-31 00:10:41,2019-03-31 00:10:27\n
16215681,702,면목P,107,중랑구,0.5,58.5,3.5,2019-03-31 00:08:41,2019-03-31 00:08:19\n
16215682,702,면목P,107,중랑구,0.5,58.5,3.5,2019-03-31 00:12:41,2019-03-31 00:11:49\n
16215683,702,면목P,107,중랑구,0.5,58.5,3.5,2019-03-31 00:13:41,2019-03-31 00:13:11\n

time_series로 변환

In [156]:
use_Data["송신지_자료수집_시각"]=use_Data["송신지_자료수집_시각"].apply(lambda x:pd.to_datetime(x))

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_6484\3798974962.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  use_Data["송신지_자료수집_시각"]=use_Data["송신지_자료수집_시각"].apply(lambda x:pd.to_datetime(x))

초 단위 제거

In [157]:
use_Data["송신지_자료수집_시각"]=use_Data["송신지_자료수집_시각"].apply(lambda x:x.replace(second=0))
use_Data

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_6484\1215499494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  use_Data["송신지_자료수집_시각"]=use_Data["송신지_자료수집_시각"].apply(lambda x:x.replace(second=0))

,강우량_코드,강우량계명,구청_코드,구청명,시우량,일년누계,최대우량,송신지_자료수집_시각,수신서버_저장_시각
166,103,개포2동,101,강남구,1.5,78.0,4.5,2019-04-09 21:33:00,2019-04-09 21:34:41\n
168,103,개포2동,101,강남구,1.5,78.0,4.5,2019-04-09 21:34:00,2019-04-09 21:35:19\n
169,103,개포2동,101,강남구,1.5,78.0,4.5,2019-04-09 21:35:00,2019-04-09 21:36:39\n
170,103,개포2동,101,강남구,1.5,78.0,4.5,2019-04-09 21:36:00,2019-04-09 21:37:20\n
171,103,개포2동,101,강남구,1.5,78.0,4.5,2019-04-09 21:37:00,2019-04-09 21:38:31\n
...,...,...,...,...,...,...,...,...,...
16215679,702,면목P,107,중랑구,0.5,58.5,3.5,2019-03-31 00:09:00,2019-03-31 00:09:01\n
16215680,702,면목P,107,중랑구,0.5,58.5,3.5,2019-03-31 00:10:00,2019-03-31 00:10:27\n
16215681,702,면목P,107,중랑구,0.5,58.5,3.5,2019-03-31 00:08:00,2019-03-31 00:08:19\n
16215682,702,면목P,107,중랑구,0.5,58.5,3.5,2019-03-31 00:12:00,2019-03-31 00:11:49\n
16215683,702,면목P,107,중랑구,0.5,58.5,3.5,2019-03-31 00:13:00,2019-03-31 00:13:11\n

살펴봐야할것
- 1. 최대우량
- 2. 시우량
- 3. 송신지_자료수집_시각

In [158]:
use_Data.sort_values(["구청명","송신지_자료수집_시각"],ascending=True,inplace=True)

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_6484\3259050076.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  use_Data.sort_values(["구청명","송신지_자료수집_시각"],ascending=True,inplace=True)

In [159]:
use_Data.drop(columns=["강우량_코드","구청_코드","수신서버_저장_시각"],inplace=True)

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_6484\2812061695.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  use_Data.drop(columns=["강우량_코드","구청_코드","수신서버_저장_시각"],inplace=True)

In [160]:
use_Data["date"]=use_Data["송신지_자료수집_시각"].apply(lambda x:f"{x.year}.{x.month}.{x.day}")
use_Data["hour"]=use_Data["송신지_자료수집_시각"].apply(lambda x:x.hour)
use_Data["min"]=use_Data["송신지_자료수집_시각"].apply(lambda x:x.minute)

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_6484\837247915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  use_Data["date"]=use_Data["송신지_자료수집_시각"].apply(lambda x:f"{x.year}.{x.month}.{x.day}")
C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_6484\837247915.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  use_Data["hour"]=use_Data["송신지_자료수집_시각"].apply(lambda x:x.hour)
C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_6484\837247915.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  use_Data["min"]=use_Data["송신지_자료수집_시각"].apply(lambda x:x.minute)

구마다 비가 온 날짜가 다름

In [163]:
groups=use_Data.groupby(["구청명"]).groups
groups_idx=[x[1] for x in groups.items()]

In [165]:
test=use_Data.loc[groups_idx[0]]
test["diff"]=test["송신지_자료수집_시각"].diff()

,강우량계명,구청명,시우량,일년누계,최대우량,송신지_자료수집_시각,date,hour,min
5792910,세곡동,강남구,0.5,0.5,0.5,2019-02-03 01:28:00,2019.2.3,1,28
5792911,세곡동,강남구,0.5,0.5,0.5,2019-02-03 01:29:00,2019.2.3,1,29
5792914,세곡동,강남구,0.5,0.5,0.5,2019-02-03 01:30:00,2019.2.3,1,30
5792912,세곡동,강남구,0.5,0.5,0.5,2019-02-03 01:31:00,2019.2.3,1,31
5792913,세곡동,강남구,0.5,0.5,0.5,2019-02-03 01:32:00,2019.2.3,1,32
...,...,...,...,...,...,...,...,...,...
13284382,세곡동,강남구,0.5,1017.0,43.5,2019-12-29 22:57:00,2019.12.29,22,57
13284363,강남구청,강남구,0.5,1052.0,29.5,2019-12-29 22:58:00,2019.12.29,22,58
13284365,강남구청,강남구,0.5,1052.0,29.5,2019-12-29 22:59:00,2019.12.29,22,59
13313294,강남구청,강남구,0.5,1052.5,29.5,2019-12-30 12:58:00,2019.12.30,12,58
13313296,강남구청,강남구,0.5,1052.5,29.5,2019-12-30 12:59:00,2019.12.30,12,59

In [183]:
use_Data.to_excel("./강우량_임시_데이터.xlsx")